version: '3'

volumes:
  ark-data:

services:
  app:
    container_name: ark
    image: hermsi/ark-server:latest
    # If you want to build from fresh source every "docker-compose up" ...
    # ... remove the "image:"-key and uncomment the following two lines:
    #build:
    #  context: ../.
    volumes:
      - ark-data:/app
    environment:
      - SESSION_NAME=${ROOT_PASSWORD}
      - SERVER_MAP=${SERVER_MAP}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - UPDATE_ON_START=${UPDATE_ON_START}
      - BACKUP_ON_START=${BACKUP_ON_START}
      - WARN_ON_STOP=${WARN_ON_STOP}
    ports:
      # Port for connections from ARK game client
      - "7777:7777"
      # Raw UDP socket port
      - "7778:7778"
      # RCON management port
      - "27020:27020"
      # Steam's server-list port
      - "27015:27015"
    networks:
      - default
